### PR TITLE
Implement first example server

### LINKED ISSUE #3: Implement a HTTP server application as a boilerplate
- Listen on the port which is given as the environment variable `PORT`
- Respond some JSON for `/`
- Respond another JSON for `/about`

### PR DESCRIPTION
**Pull request by axross**
Closes #3

- [x] Listen on the port which is given as the environment variable `PORT`
- [x] Respond some JSON for `/`
- [x] Respond another JSON for `/about`

### CODE REVIEW

**Comment by axross** [comment]
@ryotogashi Could you review these changes?

**Comment by axross** [comment]
@ryotogashi Could you review these changes?

**Review by ryonryon — APPROVED** [review]
@axross 
image

**Comment by axross** [comment]
Thanks!

**Pull request merged**
